name: smallandsimple
favicon: null
layout_spectrum: 0.20877882232889533
typography_spectrum: 0.08200577949173748
title: 'Small & Simple Things'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#501022'
    - '#c9009d'
    - '#9a3328'
    - '#b39d9f'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
