title: Small & Simple Things
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1893617
  brandStrength: 0.5021276
  lightness: 0.6875
  brandColors:
    - '#ffffff'
    - '#501022'
    - '#c9009d'
    - '#9a3328'
    - '#b39d9f'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: smallandsimple
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6446809
layout_spectrum: 1
