name: smallandsimple
favicon: null
layout_spectrum: 0.20877882232889533
typography_spectrum: 0.08200577949173748
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4576010308228433
  lightness: 0.6713773035444319
  saturation: 0.09826704068109393
  rhythmicContrast: 0.8128068959340453
purpose: []
